// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQP1N2fRN8cRVYg1GDDroPDTR7X6NHQE',
    appId: '1:721456900804:web:0c66eb2a7c5624c4653791',
    messagingSenderId: '721456900804',
    projectId: 'nursera-brainlinksoftwares',
    authDomain: 'nursera-brainlinksoftwares.firebaseapp.com',
    storageBucket: 'nursera-brainlinksoftwares.firebasestorage.app',
    measurementId: 'G-SF37YK8BLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb1hM-S3CPUN-rX88n6ErIjEK5atFvn4c',
    appId: '1:721456900804:android:78d05c2cc242744e653791',
    messagingSenderId: '721456900804',
    projectId: 'nursera-brainlinksoftwares',
    storageBucket: 'nursera-brainlinksoftwares.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCejihaKi0C_cn-gxTYUwe6e4AIqTmoBxE',
    appId: '1:721456900804:ios:92739523b9b83073653791',
    messagingSenderId: '721456900804',
    projectId: 'nursera-brainlinksoftwares',
    storageBucket: 'nursera-brainlinksoftwares.firebasestorage.app',
    iosBundleId: 'com.nursera.app.nursera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCejihaKi0C_cn-gxTYUwe6e4AIqTmoBxE',
    appId: '1:721456900804:ios:92739523b9b83073653791',
    messagingSenderId: '721456900804',
    projectId: 'nursera-brainlinksoftwares',
    storageBucket: 'nursera-brainlinksoftwares.firebasestorage.app',
    iosBundleId: 'com.nursera.app.nursera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFQP1N2fRN8cRVYg1GDDroPDTR7X6NHQE',
    appId: '1:721456900804:web:f2803334a83bd4fb653791',
    messagingSenderId: '721456900804',
    projectId: 'nursera-brainlinksoftwares',
    authDomain: 'nursera-brainlinksoftwares.firebaseapp.com',
    storageBucket: 'nursera-brainlinksoftwares.firebasestorage.app',
    measurementId: 'G-3GFPZWEL40',
  );
}
